/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author AGKF5ZZ
 */
public class Controlador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Controlador.class.getName());

    /**
     * Creates new form Controlador
     */
    public Controlador() {
        initComponents();
        
        
    } /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANELP = new javax.swing.JPanel();
        EtiquetaPrueba = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        MenuVenta = new javax.swing.JMenu();
        MenuNota = new javax.swing.JMenu();
        SubItemRN = new javax.swing.JMenuItem();
        SubItemCN = new javax.swing.JMenuItem();
        MenuInventario = new javax.swing.JMenu();
        SubItemRNC = new javax.swing.JMenuItem();
        SubItemRNP = new javax.swing.JMenuItem();
        SubItemCC = new javax.swing.JMenuItem();
        SubItemCI = new javax.swing.JMenuItem();
        MenuCaja = new javax.swing.JMenu();
        MenuConfig = new javax.swing.JMenu();
        SubItemConfigApp = new javax.swing.JMenuItem();
        SubItemConfigU = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PANELP.setBackground(new java.awt.Color(180, 211, 237));
        PANELP.setLayout(new java.awt.CardLayout());

        EtiquetaPrueba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaPrueba.setText("HOLA ES LA PANTALLA PRINCIPAL");
        EtiquetaPrueba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        PANELP.add(EtiquetaPrueba, "card2");

        MenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/casa32x32.png"))); // NOI18N
        MenuInicio.setText("Inicio");
        MenuInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuInicioMouseClicked(evt);
            }
        });
        BarraMenu.add(MenuInicio);

        MenuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/punto-de-venta32x32.png"))); // NOI18N
        MenuVenta.setText("Venta");
        MenuVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuVentaMouseClicked(evt);
            }
        });
        BarraMenu.add(MenuVenta);

        MenuNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/factura32x32.png"))); // NOI18N
        MenuNota.setText("Notas");
        MenuNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuNota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuNota.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        SubItemRN.setText("Registrar Nota");
        SubItemRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubItemRNMousePressed(evt);
            }
        });
        MenuNota.add(SubItemRN);

        SubItemCN.setText("Consultar Notas");
        SubItemCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubItemCNMousePressed(evt);
            }
        });
        SubItemCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubItemCNActionPerformed(evt);
            }
        });
        MenuNota.add(SubItemCN);

        BarraMenu.add(MenuNota);

        MenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/inventario35x35.png"))); // NOI18N
        MenuInventario.setText("Inventario");
        MenuInventario.setAlignmentY(0.4F);
        MenuInventario.setHideActionText(true);
        MenuInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        SubItemRNC.setText("Registrar Nueva Categoria");
        SubItemRNC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubItemRNCMousePressed(evt);
            }
        });
        MenuInventario.add(SubItemRNC);

        SubItemRNP.setText("Registrar Nuevo Producto");
        SubItemRNP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubItemRNPMousePressed(evt);
            }
        });
        MenuInventario.add(SubItemRNP);

        SubItemCC.setText("Consultar Categorias");
        SubItemCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubItemCCMousePressed(evt);
            }
        });
        MenuInventario.add(SubItemCC);

        SubItemCI.setText("Consultar Inventario");
        SubItemCI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubItemCIMousePressed(evt);
            }
        });
        MenuInventario.add(SubItemCI);

        BarraMenu.add(MenuInventario);

        MenuCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/cajero-automatico 30x30.png"))); // NOI18N
        MenuCaja.setText("Caja");
        MenuCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraMenu.add(MenuCaja);

        MenuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/ajuste32x32.png"))); // NOI18N
        MenuConfig.setText("Config.");
        MenuConfig.setAlignmentX(15.0F);
        MenuConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuConfig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuConfig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        SubItemConfigApp.setText("Configuraracion de app.");
        MenuConfig.add(SubItemConfigApp);

        SubItemConfigU.setText("Usuarios");
        MenuConfig.add(SubItemConfigU);

        BarraMenu.add(MenuConfig);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELP, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELP, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubItemCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubItemCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubItemCNActionPerformed

    private void MenuVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVentaMouseClicked
        // TODO add your handling code here:
        Venta v=new Venta();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(v); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
    }//GEN-LAST:event_MenuVentaMouseClicked

    private void MenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInicioMouseClicked
        // TODO add your handling code here:
        Controlador c=new Controlador();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(c.PANELP); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("A inicio");
    }//GEN-LAST:event_MenuInicioMouseClicked

    private void SubItemRNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubItemRNMousePressed
        // TODO add your handling code here:
        Notas N=new Notas();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(N); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
    }//GEN-LAST:event_SubItemRNMousePressed

    private void SubItemCNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubItemCNMousePressed
        // TODO add your handling code here:
        NotasConsulta N2=new NotasConsulta();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(N2); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
    }//GEN-LAST:event_SubItemCNMousePressed

    private void SubItemRNCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubItemRNCMousePressed
        // TODO add your handling code here:
        RegistroCategorias RC=new RegistroCategorias();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(RC); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
    }//GEN-LAST:event_SubItemRNCMousePressed

    private void SubItemCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubItemCCMousePressed
        // TODO add your handling code here:
        ConsultarCategorias CC=new ConsultarCategorias();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(CC); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
        
    }//GEN-LAST:event_SubItemCCMousePressed

    private void SubItemRNPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubItemRNPMousePressed
        // TODO add your handling code here:
        RegistroProducto RP=new RegistroProducto();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(RP); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
        
    }//GEN-LAST:event_SubItemRNPMousePressed

    private void SubItemCIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubItemCIMousePressed
        // TODO add your handling code here:
        ConsultarInventario CI=new ConsultarInventario();
        PANELP.removeAll();//remover componentes de panel
        PANELP.add(CI); //agregar la instancia al panel
        PANELP.revalidate(); //colocar el panel a instanciar
        System.out.println("se coloco la pantalla nueva");
    }//GEN-LAST:event_SubItemCIMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Controlador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JLabel EtiquetaPrueba;
    private javax.swing.JMenu MenuCaja;
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JMenu MenuNota;
    private javax.swing.JMenu MenuVenta;
    private javax.swing.JPanel PANELP;
    private javax.swing.JMenuItem SubItemCC;
    private javax.swing.JMenuItem SubItemCI;
    private javax.swing.JMenuItem SubItemCN;
    private javax.swing.JMenuItem SubItemConfigApp;
    private javax.swing.JMenuItem SubItemConfigU;
    private javax.swing.JMenuItem SubItemRN;
    private javax.swing.JMenuItem SubItemRNC;
    private javax.swing.JMenuItem SubItemRNP;
    // End of variables declaration//GEN-END:variables
}
