/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project1;

/**
 *
 * @author AGKF5ZZ
 */
public class RegistroProducto extends javax.swing.JPanel {

    /**
     * Creates new form Venta
     */
    public RegistroProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        EtiquetaDeTitulo = new javax.swing.JLabel();
        TextNCategoria = new javax.swing.JTextField();
        TextDescripcion = new javax.swing.JTextField();
        EtiqNC = new javax.swing.JLabel();
        EtiqD = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        EtiquetaId = new javax.swing.JLabel();
        EtiquetaNumeroId = new javax.swing.JLabel();
        EtiqD1 = new javax.swing.JLabel();
        TextPrecioUni = new javax.swing.JTextField();
        EtiqD2 = new javax.swing.JLabel();
        TextCantidadProducto = new javax.swing.JTextField();
        TextTotalInvercion = new javax.swing.JTextField();
        EtiqD3 = new javax.swing.JLabel();
        EtiqD4 = new javax.swing.JLabel();
        TextCodigo = new javax.swing.JTextField();
        FillerDerecho = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        FillerIzquierdo = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(180, 211, 237));

        EtiquetaDeTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EtiquetaDeTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaDeTitulo.setText("Registrar Categoria de producto");

        EtiqNC.setText("Nombre Proucto:");

        EtiqD.setText("Descripcion:");

        Registrar.setText("Registrar");

        EtiquetaId.setText("Id:");

        EtiquetaNumeroId.setText(".");

        EtiqD1.setText("Precio Unitario:");

        EtiqD2.setText("Cantidad:");

        TextCantidadProducto.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        TextTotalInvercion.setEditable(false);
        TextTotalInvercion.setAutoscrolls(false);
        TextTotalInvercion.setEnabled(false);

        EtiqD3.setText("Total de invercion:");

        EtiqD4.setText("Codigo:");

        TextCodigo.setEditable(false);
        TextCodigo.setAutoscrolls(false);
        TextCodigo.setEnabled(false);

        FillerDerecho.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        FillerIzquierdo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaDeTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FillerIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EtiquetaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiqD3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(EtiqD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiqD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiqD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiqNC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiqD4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextTotalInvercion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(TextCantidadProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextPrecioUni, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EtiquetaNumeroId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextNCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCodigo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addComponent(FillerDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(EtiquetaDeTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiquetaId)
                            .addComponent(EtiquetaNumeroId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextNCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiqNC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiqD)
                            .addComponent(TextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiqD1)
                            .addComponent(TextPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiqD2)
                            .addComponent(TextCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiqD3)
                            .addComponent(TextTotalInvercion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiqD4)
                            .addComponent(TextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Registrar))
                    .addComponent(FillerDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FillerIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiqD;
    private javax.swing.JLabel EtiqD1;
    private javax.swing.JLabel EtiqD2;
    private javax.swing.JLabel EtiqD3;
    private javax.swing.JLabel EtiqD4;
    private javax.swing.JLabel EtiqNC;
    private javax.swing.JLabel EtiquetaDeTitulo;
    private javax.swing.JLabel EtiquetaId;
    private javax.swing.JLabel EtiquetaNumeroId;
    private javax.swing.Box.Filler FillerDerecho;
    private javax.swing.Box.Filler FillerIzquierdo;
    private javax.swing.JButton Registrar;
    private javax.swing.JTextField TextCantidadProducto;
    private javax.swing.JTextField TextCodigo;
    private javax.swing.JTextField TextDescripcion;
    private javax.swing.JTextField TextNCategoria;
    private javax.swing.JTextField TextPrecioUni;
    private javax.swing.JTextField TextTotalInvercion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
